import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:get/get.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../controllers/auth_controller.dart';
import '../widgets/social_auth_button.dart';

class LoginView extends GetView<AuthController> {
  const LoginView({super.key});

  void _showPrivacyPolicy(BuildContext context) {
    Get.dialog(
      AlertDialog(
        backgroundColor: AppColors.darkSurface,
        title: const Text('Privacy Policy', style: TextStyle(color: Colors.white)),
        content: const SingleChildScrollView(
          child: Text(
            'Privacy Policy\n\n'
            '1. Data Collection: Your chat data is stored locally on your device using GetStorage.\n\n'
            '2. API Processing: Prompts submitted in chats are processed directly by the Google Gemini API.\n\n'
            '3. Storage: You have full control to clear your conversation history at any time from Settings.',
            style: TextStyle(color: AppColors.darkTextSecondary),
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Get.back(),
            child: const Text('Close', style: TextStyle(color: AppColors.primary)),
          ),
        ],
      ),
    );
  }

  void _showTerms(BuildContext context) {
    Get.dialog(
      AlertDialog(
        backgroundColor: AppColors.darkSurface,
        title: const Text('Terms & Conditions', style: TextStyle(color: Colors.white)),
        content: const SingleChildScrollView(
          child: Text(
            'Terms & Conditions\n\n'
            '1. Acceptance: By using AI Chat Assistant, you agree to comply with these terms.\n\n'
            '2. Usage: Users are responsible for the inputs submitted to the AI system.\n\n'
            '3. Disclaimer: AI responses are generated by language models and should be verified for critical decisions.',
            style: TextStyle(color: AppColors.darkTextSecondary),
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Get.back(),
            child: const Text('Close', style: TextStyle(color: AppColors.primary)),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.darkBackground,
      body: SafeArea(
        child: Center(
          child: SingleChildScrollView(
            padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 16.0),
            child: Container(
              constraints: const BoxConstraints(maxWidth: 440),
              child: Obx(() {
                if (controller.isLoading.value) {
                  return const Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      SpinKitThreeBounce(
                        color: AppColors.primary,
                        size: 36,
                      ),
                      SizedBox(height: 16),
                      Text(
                        'Signing in...',
                        style: TextStyle(color: AppColors.darkTextSecondary, fontSize: 16),
                      ),
                    ],
                  );
                }

                return Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    const SizedBox(height: 32),

                    // App Logo with Glowing Ring
                    Container(
                      width: 100,
                      height: 100,
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        boxShadow: [
                          BoxShadow(
                            color: AppColors.primary.withValues(alpha: 0.35),
                            blurRadius: 32,
                            spreadRadius: 6,
                          ),
                        ],
                      ),
                      child: ClipOval(
                        child: Image.asset(
                          'assets/images/ai_chatbot_logo.png',
                          width: 100,
                          height: 100,
                          fit: BoxFit.cover,
                        ),
                      ),
                    )
                        .animate()
                        .scale(duration: 700.ms, curve: Curves.easeOutBack)
                        .fadeIn(duration: 500.ms),

                    const SizedBox(height: 28),

                    // App Title
                    Text(
                      AppStrings.appName,
                      textAlign: TextAlign.center,
                      style: Theme.of(context).textTheme.headlineMedium?.copyWith(
                            color: Colors.white,
                            fontWeight: FontWeight.bold,
                            letterSpacing: 0.8,
                          ),
                    ).animate().fadeIn(delay: 200.ms, duration: 500.ms).slideY(begin: 0.2, end: 0),

                    const SizedBox(height: 8),

                    // Subtitle
                    Text(
                      'Powered by Gemini AI',
                      textAlign: TextAlign.center,
                      style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                            color: AppColors.darkTextSecondary,
                            fontSize: 15,
                          ),
                    ).animate().fadeIn(delay: 350.ms, duration: 500.ms),

                    const SizedBox(height: 48),

                    // Buttons Section
                    Column(
                      children: [
                        // Continue with Google Button
                        SocialAuthButton(
                          text: 'Continue with Google',
                          icon: Image.network(
                            'https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg',
                            width: 20,
                            height: 20,
                            errorBuilder: (context, error, stackTrace) => const Icon(
                              Icons.g_mobiledata_rounded,
                              color: Colors.white,
                              size: 26,
                            ),
                          ),
                          onPressed: () {
                            controller.signInWithGoogle();
                          },
                        ).animate().fadeIn(delay: 450.ms, duration: 400.ms).slideY(begin: 0.2, end: 0),

                        const SizedBox(height: 14),

                        // Continue with Apple Button
                        SocialAuthButton(
                          text: 'Continue with Apple',
                          icon: const Icon(
                            Icons.apple_rounded,
                            color: Colors.white,
                            size: 22,
                          ),
                          backgroundColor: Colors.black,
                          textColor: Colors.white,
                          onPressed: () {
                            controller.signInWithApple();
                          },
                        ).animate().fadeIn(delay: 550.ms, duration: 400.ms).slideY(begin: 0.2, end: 0),

                        const SizedBox(height: 14),

                        // Continue as Guest Button
                        SocialAuthButton(
                          text: 'Continue as Guest',
                          icon: const Icon(
                            Icons.person_outline_rounded,
                            color: AppColors.primary,
                            size: 20,
                          ),
                          isOutlined: true,
                          onPressed: () {
                            controller.signInAnonymously();
                          },
                        ).animate().fadeIn(delay: 650.ms, duration: 400.ms).slideY(begin: 0.2, end: 0),
                      ],
                    ),

                    const SizedBox(height: 48),

                    // Footer: Terms & Privacy Policy Links
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        InkWell(
                          onTap: () => _showPrivacyPolicy(context),
                          borderRadius: BorderRadius.circular(4),
                          child: const Padding(
                            padding: EdgeInsets.symmetric(horizontal: 6, vertical: 4),
                            child: Text(
                              'Privacy Policy',
                              style: TextStyle(
                                color: AppColors.darkTextSecondary,
                                fontSize: 12,
                                decoration: TextDecoration.underline,
                              ),
                            ),
                          ),
                        ),
                        const Text(
                          ' • ',
                          style: TextStyle(color: AppColors.darkTextSecondary, fontSize: 12),
                        ),
                        InkWell(
                          onTap: () => _showTerms(context),
                          borderRadius: BorderRadius.circular(4),
                          child: const Padding(
                            padding: EdgeInsets.symmetric(horizontal: 6, vertical: 4),
                            child: Text(
                              'Terms & Conditions',
                              style: TextStyle(
                                color: AppColors.darkTextSecondary,
                                fontSize: 12,
                                decoration: TextDecoration.underline,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ).animate().fadeIn(delay: 750.ms, duration: 400.ms),

                    const SizedBox(height: 16),
                  ],
                );
              }),
            ),
          ),
        ),
      ),
    );
  }
}
