import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../core/constants/app_colors.dart';
import '../../core/constants/app_strings.dart';
import '../../core/services/storage_service.dart';
import '../../core/services/theme_service.dart';
import '../home/home_controller.dart';

class SettingsController extends GetxController {
  final ThemeService themeService = Get.find<ThemeService>();
  final StorageService storageService = Get.find<StorageService>();
  final HomeController homeController = Get.find<HomeController>();

  final apiKeyController = TextEditingController();
  final selectedModel = AppStrings.defaultModel.obs;

  @override
  void onInit() {
    super.onInit();
    apiKeyController.text = storageService.apiKey ?? '';
    selectedModel.value = storageService.selectedModel;
  }

  void updateApiKey(String key) {
    if (key.trim().isEmpty) {
      storageService.removeApiKey();
    } else {
      storageService.saveApiKey(key.trim());
    }
    Get.snackbar(
      'Success',
      'API Key saved successfully',
      snackPosition: SnackPosition.TOP,
      backgroundColor: AppColors.primary,
      colorText: Colors.white,
    );
  }

  void updateSelectedModel(String model) {
    selectedModel.value = model;
    storageService.saveSelectedModel(model);
  }

  void clearAllHistory() {
    Get.dialog(
      AlertDialog(
        title: const Text('Clear All Chat History'),
        content: const Text('Are you sure you want to erase all conversations and messages? This action cannot be undone.'),
        actions: [
          TextButton(
            onPressed: () => Get.back(),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () async {
              homeController.conversations.clear();
              homeController.activeConversation.value = null;
              await storageService.clearAll();
              homeController.createNewConversation();
              Get.back();
              Get.snackbar(
                'Cleared',
                'All conversation history has been erased.',
                snackPosition: SnackPosition.TOP,
              );
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: AppColors.error,
              foregroundColor: Colors.white,
            ),
            child: const Text('Clear All'),
          ),
        ],
      ),
    );
  }

  void showAboutDialog() {
    Get.dialog(
      AboutDialog(
        applicationName: AppStrings.appName,
        applicationVersion: '1.0.0',
        applicationIcon: const Icon(Icons.auto_awesome, color: AppColors.primary, size: 40),
        children: const [
          SizedBox(height: 12),
          Text(
            'Production-Quality AI Chat Assistant built with Flutter, GetX, Clean Architecture, Material 3, and Google Gemini API.',
          ),
        ],
      ),
    );
  }

  void showPrivacyPolicy() {
    Get.dialog(
      AlertDialog(
        title: const Text('Privacy Policy'),
        content: const SingleChildScrollView(
          child: Text(
            'Privacy Policy\n\n'
            '1. Data Collection: Your chat data is stored locally on your device using GetStorage. We do not collect or send your personal data to external third-party tracking servers.\n\n'
            '2. API Communication: Prompts submitted in chats are processed directly by the Google Gemini API.\n\n'
            '3. Storage: You have full control to clear your conversation history at any time from Settings.',
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Get.back(),
            child: const Text('Close'),
          ),
        ],
      ),
    );
  }

  void showTermsOfService() {
    Get.dialog(
      AlertDialog(
        title: const Text('Terms of Service'),
        content: const SingleChildScrollView(
          child: Text(
            'Terms of Service\n\n'
            '1. Acceptance: By using AI Chat Assistant, you agree to comply with these terms.\n\n'
            '2. Usage: Users are responsible for the inputs submitted to the AI system.\n\n'
            '3. Disclaimer: AI responses are generated by language models and should be verified for critical decisions.',
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Get.back(),
            child: const Text('Close'),
          ),
        ],
      ),
    );
  }

  @override
  void onClose() {
    apiKeyController.dispose();
    super.onClose();
  }
}
